### ISSUE TITLE
App crashes when moved to landscape

### ISSUE THREAD

**Issue by pascalalfadian** [ProIfUNPAR/train-tracker-vincent-js#2]
Halo Vincent,..

App ini crash kalau dipindah dari portrait ke landscape. Kira2 bisa dibetulin ga ya? Sebenarnya cukup di [lock aja supaya jangan pindah ke landscape sih](https://stackoverflow.com/questions/5044544/lock-android-phone-application-to-portrait-mode). Kalau keburu, Juni/Juli nanti beberapa teman saya mau ke Yogya, biar bisa ditest. Kalau bagus bisa masuk Play Store.

Trims ya.

**Comment by vincentjs20** [comment]
Halo Pa Pascal,

Oke pa nanti akan saya ubah aplikasinya agar bisa ke lock layarnya, terima
kasih pa.

**Comment by pascalalfadian** [comment]
Trims ya..

**Comment by vincentjs20** [comment]
Pa Pascal, untuk aplikasinya sudah saya ubah biar orientationnya hanya
portrait. Terima kasih.

**Comment by pascalalfadian** [comment]
Halo Vincent.. Trims ya. Bisa minta tolong, kirimkan APK nya? bisa attach di sini atau share di Google Drive / etc?

**Comment by pascalalfadian** [comment]
Oh sori ternyata ada di Readme ya link nya. Itu yang terbaru, kan?

**Comment by vincentjs20** [comment]
Selamat malam pa Pascal, sori baru baca emailnya. Seharusnya yang disana
masih belum yang terbaru pa. Besok saya kirim lewat email ya pa. Terima
kasih.

**Comment by pascalalfadian** [comment]
I think this is done now.
